name: Test & Deploy #Название pipeline который будет выполнять github actions

on: [push]
#  push:
#    branches:
#      - staging # названия ветки в которую хотим пушить и запускать наш деплой

jobs:
  tests:
    name: Tests # название конктретной работы в pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  # клонируем репозиторый
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn # устанавливаем зависимости

      - name: Test
        run: yarn test # запускаем скрипт тестами

  deploy:
    name: Deploy
    needs: tests # указываем зависимую джобу т/е в данном случае деплой не запустится если тесты завершились ошибкой
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
